### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by SamuelMoller** [CodeCorrupt/godaddy-dyndns#1]
Hello!
Can this script be run on a Windows machine, or is it a Linux exclusive? I know that BASH can be used to some extent, but I'm guessing that's not the intended usage.
Thanks!

**Comment by CodeCorrupt** [comment]
Hey!
Currently I haven't tested on anything other than Fedora latest. If you have the Windows 10 update with Ubuntu embedded in it, it might work on that. 

I don't plan on porting to a native windows script anytime soon though, as I only use mac and linux at home.

**Comment by CodeCorrupt** [comment]
@Moronmaster, It was pointed out to me that Windows users might be able to run the script using [Cygwin](https://www.cygwin.com/). I have very little experience with Cygwin, but if you can, try it out and get back to me. let me know if it works, maybe run Cygwinwith the script in the windows equivalent of a cron job.
