### ISSUE TITLE
How to complete those two lines?

### ISSUE THREAD

**Issue by KittenYang** [CodeCorrupt/godaddy-dyndns#3]
<img width="356" alt="2017-02-23 00 00 48" src="https://cloud.githubusercontent.com/assets/5517281/23219909/4b600f4e-f95b-11e6-8faf-cd54bee75685.png">

I'm fresh man and I'm confusing in those two lines?What should I complete them?Thanks in advance!

**Comment by CodeCorrupt** [comment]
Hey,
This config allows for you to keep multiple records up to date.
ie: `ftp.myurl.com` `ftp.myotherurl.com` `server.myurl.com` Can all be updated by putting `myurl.com, myotherurl.com` in the domains list and `ftp, server` in the records list.

It's important to note that if there is a `server.myotherurl.com` that would also be updated by this. 

I'm also no longer actively developing this, however if there continues to be increased interest I'll patch it up.

Thanks

**Comment by KittenYang** [comment]
@CodeCorrupt Many thanks!!!

**Comment by KittenYang** [comment]
Sorry,I'm here again.I followed your steps and did this(I want to update `pi.kittenyang.com` 's ip):
<img width="361" alt="2017-02-23 01 50 11" src="https://cloud.githubusercontent.com/assets/5517281/23224753/89e8218e-f96a-11e6-9760-7a55d88ddef5.png">
I run `sudo reboot` to ensure it reboots.

But there's no `godaddy-dyndns.log` you mentioned in **README.md** nor ip updated in Godaddy.
![fullsizerender 2](https://cloud.githubusercontent.com/assets/5517281/23225197/02268090-f96c-11e6-9d0b-bb32f98279d5.jpg)

Do you have any idea?
